export const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    otpPhoneRequest: "/auth/otp/phone/request",
    otpPhoneVerify: "/auth/otp/phone/verify",
    google: "/auth/google",
    facebook: "/auth/facebook",
  },
  movies: {
    list: "/movies",
    detail: (slug: string) => `/movies/${slug}`,
    trending: "/movies/trending",
    latest: "/movies/latest",
    topRated: "/movies/top-rated",
    byCategory: (categorySlug: string) => `/movies/category/${categorySlug}`,
    search: "/movies/search",
    recommend: (slug: string) => `/movies/${slug}/recommend`,
    create: "/movies",
    update: (id: string) => `/movies/${id}`,
    remove: (id: string) => `/movies/${id}`,
    adminList: "/movies/admin/list",
    adminDetail: (id: string) => `/movies/by-id/${id}`,
  },
  reviews: {
    list: (movieId: string) => `/movies/${movieId}/reviews`,
    summary: (movieId: string) => `/movies/${movieId}/reviews/summary`,
    submit: (movieId: string) => `/movies/${movieId}/reviews`,
    like: (movieId: string, reviewId: string) => `/movies/${movieId}/reviews/${reviewId}/like`,
  },
  episodes: {
    list: (movieId: string) => `/movies/${movieId}/episodes`,
    create: (movieId: string) => `/movies/${movieId}/episodes`,
    update: (movieId: string, episodeId: string) => `/movies/${movieId}/episodes/${episodeId}`,
    remove: (movieId: string, episodeId: string) => `/movies/${movieId}/episodes/${episodeId}`,
  },
  genres: {
    list: "/genres",
  },
  banners: {
    active: "/banners",
    adminList: "/banners/admin/list",
    create: "/banners",
    update: (id: string) => `/banners/${id}`,
    remove: (id: string) => `/banners/${id}`,
  },
  videos: {
    uploadUrl: "/videos/upload-url",
    complete: (id: string) => `/videos/${id}/complete`,
    detail: (id: string) => `/videos/${id}`,
  },
  images: {
    uploadUrl: "/images/upload-url",
  },
  shorts: {
    feed: "/shorts/feed",
    like: (id: string) => `/shorts/${id}/like`,
    unlike: (id: string) => `/shorts/${id}/like`,
    create: "/shorts",
    adminList: "/shorts/admin/list",
    remove: (id: string) => `/shorts/${id}`,
  },
  subscriptions: {
    plans: "/subscriptions/plans",
    current: "/subscriptions/me",
  },
  payments: {
    checkout: "/payments/checkout",
    history: "/payments/history",
    verify: (id: string) => `/payments/verify/${id}`,
    confirm: (invoiceId: string) => `/payments/confirm/${invoiceId}`,
  },
  users: {
    me: "/users/me",
  },
  favorites: {
    list: "/favorites",
    add: "/favorites",
    remove: (movieId: string) => `/favorites/${movieId}`,
  },
  history: {
    continueWatching: "/history/continue-watching",
  },
  notifications: {
    list: "/notifications",
  },
} as const;
