export const QUERY_KEYS = {
  homeRows: ["home", "rows"] as const,
  trending: ["home", "trending"] as const,
  moviesPreview: ["home", "movies-preview"] as const,
  movieDetail: (slug: string) => ["movie", "detail", slug] as const,
  movieSearch: (query: string) => ["movie", "search", query] as const,
  moviePage: ["movie", "page"] as const,
  shortsFeed: ["shorts", "feed"] as const,
  plans: ["subscription", "plans"] as const,
  profile: ["profile", "me"] as const,
  favorites: ["profile", "favorites"] as const,
  watchHistory: ["profile", "watch-history"] as const,
  adminMovies: (page: number) => ["admin", "movies", page] as const,
  adminMovieDetail: (id: string) => ["admin", "movie", id] as const,
  heroBanners: ["home", "banners"] as const,
  adminBanners: ["admin", "banners"] as const,
  similarMovies: (slug: string) => ["movie", "similar", slug] as const,
  reviewSummary: (movieId: string) => ["reviews", "summary", movieId] as const,
  reviews: (movieId: string) => ["reviews", "list", movieId] as const,
  genres: ["genres"] as const,
  catalogPage: (page: number, genreSlug?: string) =>
    ["movie", "catalog-page", page, genreSlug ?? "all"] as const,
};
